package cl.ciisa.comunica.entity;
// Generated 02-jun-2014 22:16:48 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private Integer idAdministrador;
     private String nombreAdministrador;
     private String apellidoPaAdministrador;
     private String apellidoMatAdministrador;
     private String emailAdministrador;
     private String passwordAdministrador;
     private Date fechaRegistroAdministrador;

    public Administrador() {
    }

    public Administrador(String nombreAdministrador, String apellidoPaAdministrador, String apellidoMatAdministrador, String emailAdministrador, String passwordAdministrador, Date fechaRegistroAdministrador) {
       this.nombreAdministrador = nombreAdministrador;
       this.apellidoPaAdministrador = apellidoPaAdministrador;
       this.apellidoMatAdministrador = apellidoMatAdministrador;
       this.emailAdministrador = emailAdministrador;
       this.passwordAdministrador = passwordAdministrador;
       this.fechaRegistroAdministrador = fechaRegistroAdministrador;
    }
   
    public Integer getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(Integer idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public String getNombreAdministrador() {
        return this.nombreAdministrador;
    }
    
    public void setNombreAdministrador(String nombreAdministrador) {
        this.nombreAdministrador = nombreAdministrador;
    }
    public String getApellidoPaAdministrador() {
        return this.apellidoPaAdministrador;
    }
    
    public void setApellidoPaAdministrador(String apellidoPaAdministrador) {
        this.apellidoPaAdministrador = apellidoPaAdministrador;
    }
    public String getApellidoMatAdministrador() {
        return this.apellidoMatAdministrador;
    }
    
    public void setApellidoMatAdministrador(String apellidoMatAdministrador) {
        this.apellidoMatAdministrador = apellidoMatAdministrador;
    }
    public String getEmailAdministrador() {
        return this.emailAdministrador;
    }
    
    public void setEmailAdministrador(String emailAdministrador) {
        this.emailAdministrador = emailAdministrador;
    }
    public String getPasswordAdministrador() {
        return this.passwordAdministrador;
    }
    
    public void setPasswordAdministrador(String passwordAdministrador) {
        this.passwordAdministrador = passwordAdministrador;
    }
    public Date getFechaRegistroAdministrador() {
        return this.fechaRegistroAdministrador;
    }
    
    public void setFechaRegistroAdministrador(Date fechaRegistroAdministrador) {
        this.fechaRegistroAdministrador = fechaRegistroAdministrador;
    }




}


