package cl.ciisa.comunica.entity;
// Generated 02-jun-2014 22:16:48 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer idAlumno;
     private Curso curso;
     private String nombreAlumno;
     private String apellidoPatAlumno;
     private String apellidoMatAlumno;
     private Date fechaRegistroAlumno;
     private Set apoderados = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(Curso curso) {
        this.curso = curso;
    }
    public Alumno(Curso curso, String nombreAlumno, String apellidoPatAlumno, String apellidoMatAlumno, Date fechaRegistroAlumno, Set apoderados) {
       this.curso = curso;
       this.nombreAlumno = nombreAlumno;
       this.apellidoPatAlumno = apellidoPatAlumno;
       this.apellidoMatAlumno = apellidoMatAlumno;
       this.fechaRegistroAlumno = fechaRegistroAlumno;
       this.apoderados = apoderados;
    }
   
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNombreAlumno() {
        return this.nombreAlumno;
    }
    
    public void setNombreAlumno(String nombreAlumno) {
        this.nombreAlumno = nombreAlumno;
    }
    public String getApellidoPatAlumno() {
        return this.apellidoPatAlumno;
    }
    
    public void setApellidoPatAlumno(String apellidoPatAlumno) {
        this.apellidoPatAlumno = apellidoPatAlumno;
    }
    public String getApellidoMatAlumno() {
        return this.apellidoMatAlumno;
    }
    
    public void setApellidoMatAlumno(String apellidoMatAlumno) {
        this.apellidoMatAlumno = apellidoMatAlumno;
    }
    public Date getFechaRegistroAlumno() {
        return this.fechaRegistroAlumno;
    }
    
    public void setFechaRegistroAlumno(Date fechaRegistroAlumno) {
        this.fechaRegistroAlumno = fechaRegistroAlumno;
    }
    public Set getApoderados() {
        return this.apoderados;
    }
    
    public void setApoderados(Set apoderados) {
        this.apoderados = apoderados;
    }




}


