package cl.ciisa.comunica.entity;
// Generated 02-jun-2014 22:16:48 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Apoderado generated by hbm2java
 */
public class Apoderado  implements java.io.Serializable {


     private Integer idApoderado;
     private Alumno alumno;
     private String nombreApoderado;
     private String apellidoPatApoderado;
     private String apellidoMatApoderado;
     private String emailApoderado;
     private String passwordApoderado;
     private Date fechaRegistroApoderado;
     private Set comunicacions = new HashSet(0);

    public Apoderado() {
    }

	
    public Apoderado(Alumno alumno) {
        this.alumno = alumno;
    }
    public Apoderado(Alumno alumno, String nombreApoderado, String apellidoPatApoderado, String apellidoMatApoderado, String emailApoderado, String passwordApoderado, Date fechaRegistroApoderado, Set comunicacions) {
       this.alumno = alumno;
       this.nombreApoderado = nombreApoderado;
       this.apellidoPatApoderado = apellidoPatApoderado;
       this.apellidoMatApoderado = apellidoMatApoderado;
       this.emailApoderado = emailApoderado;
       this.passwordApoderado = passwordApoderado;
       this.fechaRegistroApoderado = fechaRegistroApoderado;
       this.comunicacions = comunicacions;
    }
   
    public Integer getIdApoderado() {
        return this.idApoderado;
    }
    
    public void setIdApoderado(Integer idApoderado) {
        this.idApoderado = idApoderado;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public String getNombreApoderado() {
        return this.nombreApoderado;
    }
    
    public void setNombreApoderado(String nombreApoderado) {
        this.nombreApoderado = nombreApoderado;
    }
    public String getApellidoPatApoderado() {
        return this.apellidoPatApoderado;
    }
    
    public void setApellidoPatApoderado(String apellidoPatApoderado) {
        this.apellidoPatApoderado = apellidoPatApoderado;
    }
    public String getApellidoMatApoderado() {
        return this.apellidoMatApoderado;
    }
    
    public void setApellidoMatApoderado(String apellidoMatApoderado) {
        this.apellidoMatApoderado = apellidoMatApoderado;
    }
    public String getEmailApoderado() {
        return this.emailApoderado;
    }
    
    public void setEmailApoderado(String emailApoderado) {
        this.emailApoderado = emailApoderado;
    }
    public String getPasswordApoderado() {
        return this.passwordApoderado;
    }
    
    public void setPasswordApoderado(String passwordApoderado) {
        this.passwordApoderado = passwordApoderado;
    }
    public Date getFechaRegistroApoderado() {
        return this.fechaRegistroApoderado;
    }
    
    public void setFechaRegistroApoderado(Date fechaRegistroApoderado) {
        this.fechaRegistroApoderado = fechaRegistroApoderado;
    }
    public Set getComunicacions() {
        return this.comunicacions;
    }
    
    public void setComunicacions(Set comunicacions) {
        this.comunicacions = comunicacions;
    }




}


