package cl.ciisa.comunica.entity;
// Generated 02-jun-2014 22:16:48 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Comunicacion generated by hbm2java
 */
public class Comunicacion  implements java.io.Serializable {


     private Integer idComunicacion;
     private Profesor profesor;
     private Apoderado apoderado;
     private Set detallecomunicacions = new HashSet(0);

    public Comunicacion() {
    }

	
    public Comunicacion(Profesor profesor, Apoderado apoderado) {
        this.profesor = profesor;
        this.apoderado = apoderado;
    }
    public Comunicacion(Profesor profesor, Apoderado apoderado, Set detallecomunicacions) {
       this.profesor = profesor;
       this.apoderado = apoderado;
       this.detallecomunicacions = detallecomunicacions;
    }
   
    public Integer getIdComunicacion() {
        return this.idComunicacion;
    }
    
    public void setIdComunicacion(Integer idComunicacion) {
        this.idComunicacion = idComunicacion;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Apoderado getApoderado() {
        return this.apoderado;
    }
    
    public void setApoderado(Apoderado apoderado) {
        this.apoderado = apoderado;
    }
    public Set getDetallecomunicacions() {
        return this.detallecomunicacions;
    }
    
    public void setDetallecomunicacions(Set detallecomunicacions) {
        this.detallecomunicacions = detallecomunicacions;
    }




}


