package cl.ciisa.comunica.entity;
// Generated 02-jun-2014 22:16:48 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Detallecomunicacion generated by hbm2java
 */
public class Detallecomunicacion  implements java.io.Serializable {


     private Integer idDetalleComunicacion;
     private Comunicacion comunicacion;
     private String asunto;
     private String mensaje;
     private Date fechaRegistroComunicacion;
     private Integer emisor;
     private Integer destinatario;
     private Boolean estado;

    public Detallecomunicacion() {
    }

	
    public Detallecomunicacion(Comunicacion comunicacion) {
        this.comunicacion = comunicacion;
    }
    public Detallecomunicacion(Comunicacion comunicacion, String asunto, String mensaje, Date fechaRegistroComunicacion, Integer emisor, Integer destinatario, Boolean estado) {
       this.comunicacion = comunicacion;
       this.asunto = asunto;
       this.mensaje = mensaje;
       this.fechaRegistroComunicacion = fechaRegistroComunicacion;
       this.emisor = emisor;
       this.destinatario = destinatario;
       this.estado = estado;
    }
   
    public Integer getIdDetalleComunicacion() {
        return this.idDetalleComunicacion;
    }
    
    public void setIdDetalleComunicacion(Integer idDetalleComunicacion) {
        this.idDetalleComunicacion = idDetalleComunicacion;
    }
    public Comunicacion getComunicacion() {
        return this.comunicacion;
    }
    
    public void setComunicacion(Comunicacion comunicacion) {
        this.comunicacion = comunicacion;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public Date getFechaRegistroComunicacion() {
        return this.fechaRegistroComunicacion;
    }
    
    public void setFechaRegistroComunicacion(Date fechaRegistroComunicacion) {
        this.fechaRegistroComunicacion = fechaRegistroComunicacion;
    }
    public Integer getEmisor() {
        return this.emisor;
    }
    
    public void setEmisor(Integer emisor) {
        this.emisor = emisor;
    }
    public Integer getDestinatario() {
        return this.destinatario;
    }
    
    public void setDestinatario(Integer destinatario) {
        this.destinatario = destinatario;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


