package cl.ciisa.comunica.entity;
// Generated 02-jun-2014 22:16:48 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer idProfesor;
     private Curso curso;
     private String nombreProfesor;
     private String apellidoPatProfesor;
     private String apellidoMatProfesor;
     private String emailProfesor;
     private String passwordProfesor;
     private Date fechaRegistroProfesor;
     private Set comunicacions = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(Curso curso) {
        this.curso = curso;
    }
    public Profesor(Curso curso, String nombreProfesor, String apellidoPatProfesor, String apellidoMatProfesor, String emailProfesor, String passwordProfesor, Date fechaRegistroProfesor, Set comunicacions) {
       this.curso = curso;
       this.nombreProfesor = nombreProfesor;
       this.apellidoPatProfesor = apellidoPatProfesor;
       this.apellidoMatProfesor = apellidoMatProfesor;
       this.emailProfesor = emailProfesor;
       this.passwordProfesor = passwordProfesor;
       this.fechaRegistroProfesor = fechaRegistroProfesor;
       this.comunicacions = comunicacions;
    }
   
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNombreProfesor() {
        return this.nombreProfesor;
    }
    
    public void setNombreProfesor(String nombreProfesor) {
        this.nombreProfesor = nombreProfesor;
    }
    public String getApellidoPatProfesor() {
        return this.apellidoPatProfesor;
    }
    
    public void setApellidoPatProfesor(String apellidoPatProfesor) {
        this.apellidoPatProfesor = apellidoPatProfesor;
    }
    public String getApellidoMatProfesor() {
        return this.apellidoMatProfesor;
    }
    
    public void setApellidoMatProfesor(String apellidoMatProfesor) {
        this.apellidoMatProfesor = apellidoMatProfesor;
    }
    public String getEmailProfesor() {
        return this.emailProfesor;
    }
    
    public void setEmailProfesor(String emailProfesor) {
        this.emailProfesor = emailProfesor;
    }
    public String getPasswordProfesor() {
        return this.passwordProfesor;
    }
    
    public void setPasswordProfesor(String passwordProfesor) {
        this.passwordProfesor = passwordProfesor;
    }
    public Date getFechaRegistroProfesor() {
        return this.fechaRegistroProfesor;
    }
    
    public void setFechaRegistroProfesor(Date fechaRegistroProfesor) {
        this.fechaRegistroProfesor = fechaRegistroProfesor;
    }
    public Set getComunicacions() {
        return this.comunicacions;
    }
    
    public void setComunicacions(Set comunicacions) {
        this.comunicacions = comunicacions;
    }




}


